[site]
title = "Yutong Yue"
description = "M.S. Student at Peking University"
favicon = "/favicon.svg"
last_updated = "April 9, 2026"

[author]
name = "Yutong Yue"
title = "M.S. Student"
institution = "Peking University"
avatar = "/bio.jpg"

[social]

email = "yyt@stu.pku.edu.cn"
location = "Shenzhen, China"
location_url = "https://maps.google.com"
location_details = [
  "School of Electronic and Computer Engineering,",
  "Peking University Shenzhen Graduate School"
]
google_scholar = ""
orcid = ""
github = ""
linkedin = ""

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false



[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Misc"
type = "page"
target = "misc"
href = "/misc"
